### ISSUE TITLE
Names with leading @ produce "Cannot load resource"

### ISSUE THREAD

**Issue by SteveSandersonMS** [mrlacey/DemoSnippets#13]
I totally love this extension! Thanks for releasing it, @mrlacey! One minor issue I noticed:

### Installed product versions
- Visual Studio: 2019 Enterprise Preview 2
- This extension: 1.6

### Description

Can't use a leading `@` on snippet names

### Steps to recreate

```
- @My title
Hello
```

### Current behavior

![image](https://user-images.githubusercontent.com/1101362/51975684-c28ad800-247a-11e9-89bc-2a2e823d76aa.png)

### Expected behavior

Displaying the text as written (including the leading `@`, which is not intended to have any special meaning to the tool AFAIK).

**Comment by mrlacey** [comment]
Internally, the Toolbox uses strings that start with '@' as an indicator of an embedded resource.
I've added a workaround for this so that you can use Labels that start with this character. This will be available in version 1.7 - coming soon.

**Comment by mrlacey** [comment]
> version 1.7 - coming soon.

very soon. It's in the marketplace now!

**Comment by SteveSandersonMS** [comment]
Wow, amazingly fast!
