### ISSUE TITLE
Will this be available for VS 2022?

### ISSUE THREAD

**Issue by chrissainty** [mrlacey/DemoSnippets#17]
I can't install the existing version with VS 2022. Are there plans to update this for VS 2022?

**Comment by mrlacey** [comment]
Sorry for the delayed response. Recent illness has stopped me from working on anything but I hope to get to this eventually.

**Comment by chrissainty** [comment]
Please don't apologise. I know how hard it is fitting everything in. I'm happy to help out if you'd like?

**Comment by mrlacey** [comment]
Sorry it took so long but it's there now: https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.DemoSnippets

LMK if you have any other feedback or find any issues
