### ISSUE TITLE
Auto load .demosnippets on solution open & remove on close

### ISSUE THREAD

**Issue by clairernovotny** [mrlacey/DemoSnippets#4]
When a solution is opened that contains a `.demosnippets` solution item, it would be nice if they were automatically loaded to the toolbox.

Likewise, on solution close/unload, it would be nice if the extension could remove the tabs it created (is there a way to tag them so it doesn't mess up things it didn't add)?

**Comment by mrlacey** [comment]
This behavior is included by default in v1.2 but can be opted out via settings: Tools > Options > DemoSnippets

![image](https://user-images.githubusercontent.com/189547/51089095-9b849480-175f-11e9-8261-0f473c329d23.png)

Depending on how many extensions (and which ones) are installed it may take a few seconds before this extension is loaded and can update the toolbox. Click the button on the far left of the status bar to watch extensions load and background packages run.
![image](https://user-images.githubusercontent.com/189547/51089209-637e5100-1761-11e9-8c1b-2243f29100e6.png)

Note this loads all *.demosnippets files in the same directory as the sln file (and below) whether they are part of the solution or not. This is becuase it's much faster and less error prone than querying the solution directly. (Different project types list files in very different ways.) If a solution links to .demosnippets files outside of the directory root they won't be loaded.

Note also, that if you close a solution while VS is still open, it will also remove any empty tabs created so hold demosnippets. If VS is closed without first closing the solution, the empty tabs will be left. This is a side-effect of how the Toolbox works with VS lifecycle events. If it's a big issue I could add an option to remove empty tabs and also have it run on project start up.

Additionally, what is processed during auto-load (and other important info--including exceptions) is written to a new output pane.
![image](https://user-images.githubusercontent.com/189547/51089088-4ea0be00-175f-11e9-829a-8a9794aff31a.png)

If more or less than was expected is loaded, this should help explain why.

**Comment by mrlacey** [comment]
functionality added to v1.2 - currently going through VSMarketplace verification and shoudl be available shortly.
