### ISSUE TITLE
Prevent duplication of toolbox items when loading the same file repeatedly

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/DemoSnippets#6]
If loading a file repeatedly, do not create duplicate entries in the Toolbox. 

Existing items with the same label should be overwritten.

New labeled items will be added.

Do not (at least initially) remove items from the toolbox that have been removed (or relabelled) - wait for someone to ask for this. For now, these will be left and can be removed individually or as part of removing all demosnippets.

Do not apply to over-writing of items with the same label but from different files. - Having multiple items with duplicate labels could still be confusing but not something to actively prevent. Someone might have a good reason for wanting that.

**Comment by clairernovotny** [comment]
I would think that demo snippets should be removed when they’re not in scope as you’ve implemented it. The trick may be to only remove the things you’ve added, I’m not sure if there’s a way to tag the toolbox items to determine that.

**Comment by mrlacey** [comment]
Yes, this is easy to do, just making a note here that it needs doing
